/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package structword;

import java.io.File;
import java.io.IOException;
import java.util.HashMap;

import com.deepoove.poi.XWPFTemplate;

public class App {
    /**
     * @return
     * @throws IOException
     */
    public String getGreeting() {

        try {
            File file = new File("template.docx");

            if(file.exists())
            {
                XWPFTemplate.compile(file.getPath()).render(new HashMap<String, Object>() {
                    {
                        put("title", "poi-tl模板文件");
                        put("userName", "测试用户");
                    }
                }).writeToFile("out_template.docx");
            }
            File directory = new File("."); 
            System.out.println(directory.getCanonicalPath()); 
        } 
        catch (IOException e) {

        }
       
        return "模板测试";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
